package com.example.confluence.sso.oidc;

import com.example.confluence.sso.config.SSOConfig;
import com.nimbusds.oauth2.sdk.*;
import com.nimbusds.oauth2.sdk.auth.ClientSecretBasic;
import com.nimbusds.oauth2.sdk.auth.Secret;
import com.nimbusds.oauth2.sdk.http.HTTPResponse;
import com.nimbusds.oauth2.sdk.id.ClientID;
import com.nimbusds.oauth2.sdk.id.Issuer;
import com.nimbusds.oauth2.sdk.id.State;
import com.nimbusds.oauth2.sdk.pkce.CodeChallengeMethod;
import com.nimbusds.oauth2.sdk.pkce.CodeVerifier;
import com.nimbusds.openid.connect.sdk.*;
import com.nimbusds.openid.connect.sdk.claims.UserInfo;
import com.nimbusds.openid.connect.sdk.op.OIDCProviderMetadata;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.net.URI;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * OIDC / OAuth 2.0 Authorization Code handler using Nimbus OAuth2 SDK.
 *
 * Supports:
 * <ul>
 *   <li>Auto-discovery via {@code /.well-known/openid-configuration}</li>
 *   <li>PKCE (S256) — enabled by default, toggleable via config</li>
 *   <li>ID token and UserInfo endpoint for user attributes</li>
 * </ul>
 */
public class OIDCHandler {

    private static final Logger log = LoggerFactory.getLogger(OIDCHandler.class);

    private final SSOConfig config;
    private volatile OIDCProviderMetadata providerMetadata;

    /** In-flight state → PKCE verifier mapping. In a cluster, use a distributed store. */
    private final Map<String, String> pendingStates = new ConcurrentHashMap<>();

    public OIDCHandler(SSOConfig config) {
        this.config = config;
    }

    // ── Step 1: build authorization URL ──────────────────────────────────────

    /**
     * Build the authorization redirect URL and store the PKCE verifier.
     *
     * @param state  random state value (generated by the caller, stored in session)
     * @return the full authorization endpoint URL to redirect the user to
     */
    public String buildAuthorizationUrl(String state) throws Exception {
        OIDCProviderMetadata meta = getProviderMetadata();

        State nimbusState = new State(state);
        Nonce nonce       = new Nonce();

        AuthorizationRequest.Builder builder = new AuthorizationRequest.Builder(
            new ResponseType(ResponseType.Value.CODE),
            new ClientID(config.getOidcClientId()))
            .endpointURI(meta.getAuthorizationEndpointURI())
            .redirectionURI(new URI(config.getOidcRedirectUri()))
            .state(nimbusState)
            .scope(Scope.parse(config.getOidcScopes()));

        // Add PKCE if enabled
        if (config.isOidcPkceEnabled()) {
            CodeVerifier verifier = new CodeVerifier();
            pendingStates.put(state, verifier.getValue());
            builder.codeChallenge(verifier, CodeChallengeMethod.S256);
        } else {
            pendingStates.put(state, null);
        }

        return builder.build().toURI().toString();
    }

    // ── Step 2: exchange code for tokens + fetch UserInfo ─────────────────────

    /**
     * Exchange the authorization code received in the callback for an access token,
     * then fetch the UserInfo endpoint to get user attributes.
     *
     * @param code       authorization code from the query parameter
     * @param state      state value from the query parameter (must match session value)
     * @return populated {@link OIDCUserInfo}
     */
    public OIDCUserInfo exchangeCodeAndFetchUser(String code, String state) throws Exception {
        if (!pendingStates.containsKey(state)) {
            throw new OIDCException("Unknown or expired OAuth state — possible CSRF.");
        }

        String codeVerifierValue = pendingStates.remove(state);
        OIDCProviderMetadata meta = getProviderMetadata();

        // Build token request
        AuthorizationCode authCode    = new AuthorizationCode(code);
        URI               redirectUri = new URI(config.getOidcRedirectUri());
        ClientID          clientId    = new ClientID(config.getOidcClientId());
        Secret            clientSecret = new Secret(config.getOidcClientSecret());

        AuthorizationCodeGrant grant = (codeVerifierValue != null)
            ? new AuthorizationCodeGrant(authCode, redirectUri, new CodeVerifier(codeVerifierValue))
            : new AuthorizationCodeGrant(authCode, redirectUri);

        TokenRequest tokenRequest = new TokenRequest(
            meta.getTokenEndpointURI(),
            new ClientSecretBasic(clientId, clientSecret),
            grant,
            Scope.parse(config.getOidcScopes()));

        HTTPResponse tokenHttpResp = tokenRequest.toHTTPRequest().send();
        OIDCTokenResponse tokenResponse;
        try {
            tokenResponse = OIDCTokenResponse.parse(tokenHttpResp);
        } catch (ParseException e) {
            throw new OIDCException("Failed to parse token response: " + e.getMessage(), e);
        }

        if (!tokenResponse.indicatesSuccess()) {
            TokenErrorResponse err = tokenResponse.toErrorResponse();
            throw new OIDCException("Token endpoint error: " + err.getErrorObject().getDescription());
        }

        OIDCTokenResponse successResponse = tokenResponse.toSuccessResponse();
        com.nimbusds.oauth2.sdk.token.BearerAccessToken accessToken =
            successResponse.getOIDCTokens().getBearerAccessToken();

        // Fetch UserInfo
        UserInfoRequest uiReq = new UserInfoRequest(meta.getUserInfoEndpointURI(), accessToken);
        HTTPResponse    uiHttp = uiReq.toHTTPRequest().send();
        UserInfoResponse uiResp;
        try {
            uiResp = UserInfoResponse.parse(uiHttp);
        } catch (ParseException e) {
            throw new OIDCException("Failed to parse UserInfo response: " + e.getMessage(), e);
        }

        if (!uiResp.indicatesSuccess()) {
            throw new OIDCException("UserInfo endpoint error: " +
                uiResp.toErrorResponse().getErrorObject().getDescription());
        }

        UserInfo userInfo = uiResp.toSuccessResponse().getUserInfo();

        return extractUserInfo(userInfo);
    }

    // ── OIDC Discovery ────────────────────────────────────────────────────────

    /** Lazily fetch and cache the OIDC provider metadata. */
    public OIDCProviderMetadata getProviderMetadata() throws Exception {
        if (providerMetadata == null) {
            synchronized (this) {
                if (providerMetadata == null) {
                    Issuer issuer = new Issuer(config.getOidcIssuerUrl());
                    com.nimbusds.openid.connect.sdk.op.OIDCProviderConfigurationRequest req =
                        new com.nimbusds.openid.connect.sdk.op.OIDCProviderConfigurationRequest(issuer);
                    HTTPResponse httpResp = req.toHTTPRequest().send();
                    providerMetadata = OIDCProviderMetadata.parse(httpResp.getContentAsJSONObject());
                    log.info("Loaded OIDC provider metadata from {}", config.getOidcIssuerUrl());
                }
            }
        }
        return providerMetadata;
    }

    /** Force a refresh of cached provider metadata (e.g. after config change). */
    public synchronized void resetProviderMetadata() {
        providerMetadata = null;
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private OIDCUserInfo extractUserInfo(UserInfo userInfo) {
        String email    = userInfo.getStringClaim(config.getOidcClaimEmail());
        String fullName = userInfo.getStringClaim(config.getOidcClaimFullName());
        String subject  = userInfo.getSubject() != null ? userInfo.getSubject().getValue() : null;

        java.util.List<String> groups = new java.util.ArrayList<>();
        Object groupsClaim = userInfo.getClaim(config.getOidcClaimGroups());
        if (groupsClaim instanceof java.util.List) {
            for (Object g : (java.util.List<?>) groupsClaim) {
                if (g != null) groups.add(g.toString());
            }
        }

        return new OIDCUserInfo(subject, email, fullName, groups);
    }
}
